chad:
  botToken: ""
  databaseFile: data.db
  enableNotificationRoles: true
  notificationChannelId: 701824005954600960
  removedContentChannelId: 1234567890
  welcomeChannelId: 708732557453426728
  gameChatChannelId: 475124545687388160
  statusChannelId: 701102820409212968
  serverId: 116914772766752769
  ingameBotRoleId: 554881659950858251
  playingMessage: "with Kotlin"
  commandChar: ','
  disableSpoilers: true
  notifications:
    - role: "Survival"
      emoji: "🇸"
      name: "🇸urvival"
      description: "Survival updates"
    - role: "Modded"
      emoji: "🇲"
      name: "🇲odded"
      description: "Modded updates"
    - role: "Updates"
      emoji: "🇺"
      name: "🇺pdates"
      description: "Network updates"
  fractalDeets:
    size: 2048
    maxIterations: 10000
    messiness: 30
    zoom: 3.5
  authorizedDiscordRoles:
    - "Staff"
  logging:
    defaultLevel: "warn"
    chadLevel: "debug"
    dateTimeFormat: "[yyyy-MM-dd HH:mm:ss]"
  greetings:
    - "Welcome to ORE, @USER! Make sure to run `/discord` ingame and link your account to view the rest of DiscOREd!"
    - "Oh hi, @USER! Run `/discord` ingame to link your account to view the rest of DiscOREd!"
    - "Welcome, @USER! To see the rest of our DiscOREd, link your account by running `/discord` ingame!"
  insults:
    - "once in the 4th grade %USER% got a 2% on their math quiz so everyone called them milk for the rest of the year"
    - "%USER% may look like an idiot and talk like an idiot but don't let that fool you. %USER% really is an idiot."
    - "%USER%, you warthog-faced buffoon."
    - "%USER%, I fart in your general direction. Your mother was a hamster and your father smelt of elderberries."
    - "%USER% has no enemies, but is intensely disliked by their friends."
    - "%USER% is a cockalorum."
    - "%USER% ........ pillock."
    - "%USER% is more disappointing than an unsalted pretzel."
    - "%USER% is the reason God created the middle finger."
    - "I’ll never forget the first time I met %USER%. But I’ll keep trying."
    - "Hold still. I’m trying to imagine %USER% with a personality."
